services:
  vue-base:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-base
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c 'npm i && npm run dev'
    restart: always
